format_version: 3
pipelines:
  quickstart_app:
    lock_behavior: lockOnFailure
    group: Quick
    materials:
      repo: 
       git: https://github.com/devops-at06/MC.git
       branch: master 
    stages: 
      - Build:
          jobs:
            building: 
              tasks:
                - exec:
                    command: ./gradle/quickstart/gradlew
                    arguments:
                      - "clean"
                      - "assemble"
                      - "-p"
                      - "gradle/quickstart/"
              artifacts:
                - build:
                    source: gradle/quickstart/build/libs/*.jar
                    destination: Build
      - Test:
          jobs:
            Unit_Test: 
              tasks:
                - exec:
                    command: ./gradle/quickstart/gradlew
                    arguments:
                      - clean
                      - test
                      - -p
                      - gradle/quickstart
              artifacts:
                - build:
                    source: gradle/quickstart/build/reports/tests/test/**/*
                    destination: html
                - test:
                    source: gradle/quickstart/build/test-results/test/*xml
                    destination: xml
              tabs:
                unit_test: html/index.html
      - Sonarqube:
          jobs:
            analyzing: 
              tasks:
                - exec:
                    command: ./gradle/quickstart/gradlew
                    arguments:
                      - "sonarqube"
                      - "-p"
                      - "gradle/quickstart/"

  quickstart_webapp:
    lock_behavior: lockOnFailure
    group: Quick
    materials:
      repo: 
       git: https://github.com/PanDeBatalla94/MC.git
       branch: task12 
    stages: 
      - Commit:
          jobs:
            building: 
              tasks:
                - exec:
                    command: ./gradle/quickstart-web/gradlew
                    arguments:
                      - "clean"
                      - "assemble"
                      - "-p"
                      - "gradle/quickstart-web/"
              artifacts:
                - build:
                    source: gradle/quickstart-web/build/libs/*.war
                    destination: war
      - Test:
          jobs:
            Unit_Test: 
              tasks:
                - exec:
                    command: ./gradle/quickstart-web/gradlew
                    arguments:
                      - test
                      - jacocoTestReport
                      - -p
                      - gradle/quickstart-web/
              artifacts:
                - build:
                    source: gradle/quickstart-web/build/reports/tests/test/**/*
                    destination: html
                - test:
                    source: gradle/quickstart-web/build/test-results/test/*xml
                    destination: xml               
                - build:
                    source: gradle/quickstart-web/build/jacocoHtml/**/*
                    destination: jacoco
              tabs:
                unit_test: html/index.html
                jacoco: jacoco/index.html
      - Sonarqube:
          jobs:
            analyzing: 
              tasks:
                - exec:
                    command: ./gradle/quickstart-web/gradlew
                    arguments:
                      - "sonarqube"
      - Deploy:
          jobs:
            deploying: 
              tasks:
                - fetch:
                    stage: Commit
                    job: building
                    source: war/

                - exec:
                    command: ./gradle/quickstart-web/gradlew
                    arguments:
                      - -b
                      - deploy.gradle
                      - deploy
                      - -Pdev_server=10.28.135.235
                      - -Puser_home=/home/go
                      - -Pwar_path=war
                      - -p
                      - gradle/quickstart-web/


 
 
