@echo off
set OS_AUTH_URL=http://10.28.3.240:5000/v3
set OS_IDENTITY_API_VERSION=3
set OS_TENANT_NAME=
set OS_PROJECT_NAME=
set OS_USERNAME=
set OS_PASSWORD=
set OS_DOMAIN_NAME=
set OS_FLAVOR=
set OS_IMAGE=
set OS_KEY_PAIR_NAME=
set OS_REGION_NAME=
set OS_FLAVOR=

set OS_PROJECT_NAME_DEP=
set OS_FLAVOR_DEP=
set OS_TENANT_NAME_DEP=
