version: '3'
<<<<<<< HEAD
services: 
  gocd_server:   
    image: "registry.fundacion-jala.local/devops/gocd/gocd-server:v18.5.0" 
    ports:      
      - "8153:8153"     
      - "8154:8154"    
=======
services:
  gocd_server:    
    image: "registry.fundacion-jala.local/devops/gocd/gocd-server:v18.5.0" 
    ports:     
      - "8153:8153"     
      - "8154:8154"   
>>>>>>> modifications docker-compose for gocd
    volumes:      
      - /home/ubuntu/dockerGoCD/godata_server:/godata      
      - /home/ubuntu/dockerGoCD/go_server:/home/go  
  gocd_agent:    
<<<<<<< HEAD
    image: "registry.fundacion-jala.local/devops/gocd/gocd-agent-alpine-3.7:v18.5.0"    
    environment:      
      - GO_SERVER_URL=https://gocd_server:8154/go
    volumes:      
      - /home/ubuntu/dockerGoCD/godata_agent:/godata      
=======
    image: "registry.fundacion-jala.local/devops/gocd/gocd-agent-alpine-3.7:v18.5.0"   
    environment:      
      - GO_SERVER_URL=https://gocd_server:8154/go
    volumes:      
      - /home/ubuntu/dockerGoCD/godata_agent:/godata     
>>>>>>> modifications docker-compose for gocd
      - /home/ubuntu/dockerGoCD/go_agent:/home/go
      
